### ISSUE TITLE
Builds

### ISSUE THREAD

**Issue by pcasaretto** [bgentry/heroku-go#18]
Hello,

I noticed the current API does not encompass the builds API.
I tried to generate it using `gen.rb` but it fails with the most up-to-date schema.
Any way I can help? :)

**Comment by bgentry** [comment]
Unfortunately that script fell behind awhile ago. At one point @cyberdelia was working on a better one, but I'm not sure whether that's still being developed or not.

The ruby script is a very brute force way of generating the client and isn't an intelligent parser or anything like that. So it's pretty tough to maintain as the complexity of the API has grown.

So that's where it's at... I haven't had any need to try to get the script working again and I'm not sure how much effort it would even take. Maybe in the past 1.5 years somebody else has written a JSON schema client in Golang?

**Comment by pcasaretto** [comment]
Maybe we can use this guy https://github.com/interagent/schematic .
I'll have a crack at it and see how it goes.

**Comment by cyberdelia** [comment]
[cyberdelia/heroku-go](https://github.com/cyberdelia/heroku-go) is kept up-to-date fairly often.
